### ISSUE TITLE
Bottle docs

### ISSUE THREAD

**Issue by theNerd247** [ksubcm/website#23]
Because I'm so new to bottle I have no idea what's going on with the file setup you added. Could you append to the README.md: 
- dependencies for your setup (I had a bit of trouble because I didn't know that jinja2 was needed)
- explanation of dir layout for python/bottle related files (just something quick so I can follow what you're doing) 
- high-level logical flow of the setup we plan on doing.

**Comment by StephenStrickland** [comment]
@theNerd247 done.

**Comment by theNerd247** [comment]
fixed with: f4e0a4e6cb3435010807fc5c21eed9804400801f
